---
  # This playbook deploys the troup system nodes

- name: configure and install troup nodes
  hosts: vcluster
  remote_user: ansible

  tasks:
    - name: install python3 (ensure version 3.4)
      apt:
        name: python3.4
      become: true
    - name: install python2 (ensure version 2.7)
      apt:
        name: python2.7
      become: true
    - name: install pip3 (for python 3.4)
      apt:
        name: python3-pip
        state: latest
      become: true
    - name: install pip (for python 2.7)
      apt:
        name: python-pip
        state: latest
      become: true
    - name: install supervisord
      pip:
        executable: pip
        name: supervisor
        state: latest
      become: true
    - name: install troup
      pip:
        executable: pip3
        name: troup
        state: latest
      become: true
    - name: Add troup user
      user:
        name: troup
        shell: /bin/false
        createhome: no
        generate_ssh_key: yes
        group: troup
        ssh_key_bits: 2048
        ssh_key_file: ~/.ssh/id_rsa
