---
  # This playbook deploys the troup system nodes

- name: configure and install troup nodes
  hosts: vcluster
  remote_user: ansible

  tasks:
    - name: install python3 (ensure version 3.4)
      apt:
        name: python3.4
    - name: install pip (for python 3.4)
      apt:
        name: python3-pip
        state: latest
